name: MacOS

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  macos:
    if: github.event.pull_request.draft == false
    runs-on: macos-latest
    name: Compilation and unittests.

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2

    - name: Compilation check
      run: |
        ./configure.sh
        ./build.sh

    - name: Unittests
      run: |
        ./test.sh
