name: MacOS

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest
    name: Compatibility checks.

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2

    - name: Compilation check
      run: |
        ./configure.sh
        ./build.sh
