name: Unittests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  unittests:
    runs-on: ubuntu-latest
    name: Compile and run unittests

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2

    - name: Run all unittests
      run: |
        ./configure.sh
        ./build.sh
        ./test.sh
